### ISSUE TITLE
getting a error

### ISSUE THREAD

**Issue by TheBaconSpace** [StreamStats/PlayerStats#2]
@kayteh @Rushmead https://surl.im/i/9j4q4

**Comment by Rushmead** [comment]
Send me the C9 Enviro @TheBaconSpace

**Comment by TheBaconSpace** [comment]
Can u Go on [Discord](https://discord.gg/0ovYHPQcrJsvF1mx) pls

**Comment by Rushmead** [comment]
@TheBaconSpace Not at the moment. Just send me the link

**Comment by TheBaconSpace** [comment]
@Rushmead i sent u it on twitter didnt feel like posting on here

**Comment by TheBaconSpace** [comment]
[here](https://ide.c9.io/thebaconspaces/playerstats)
